### ISSUE TITLE
Version Healthy / Version Bière

### ISSUE THREAD

**Issue by Adaendra** [apomalyn/Candybox-3#2]
Faire une option pour pouvoir passer des bonbons à des navets ou des bières

**Comment by apomalyn** [comment]
Évidemment ca va changer le visuel de tout. genre pour la version bière on va avoir une brasserie pour la ferme :D

**Comment by Adaendra** [comment]
> 
> 
> Évidemment ca va changer le visuel de tout. genre pour la version bière on va avoir une brasserie pour la ferme :D

Forcément!
